apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: thesis.unipi.gr
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: unipi.gr
  # list of versions supported by this CustomResourceDefinition
  scope: Namespaced
  names:
    kind: Thesi
    singular: thesi
    plural: thesis
    shortNames:
      - th
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string