apiVersion: apps/v1
kind: Deployment
metadata:
  name: requester-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requester
  template:
    metadata:
      labels:
        app: requester
    spec:
      containers:
      - name: requester
        image: kostaschikis/requester:latest
        env:
        - name: "LB"
          value: http://flask:5000/app
        ports:
        - containerPort: 5000