# Mongo App and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: uni-work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
# !!! This name will be used for MONGO HOSTNAME !!!
metadata:
  name: mongo
  namespace: uni-work
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---

# Flask App and Service 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: uni-work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: kostaschikis/pstesterws:latest
        resources:
          limits:
            memory: 100M
            # 0.5 Cpu cores
            cpu: 500m
        env:
        - name: MONGO_HOSTNAME
          value: mongo
        - name: MONGO_PORT
          value: '27017'
        - name: EXECUTION_CONTEXT
          value: 'K8S'
        - name: METRICS_EXPOSING_METHOD
          value: PULL
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: uni-work
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007
